.TH test.sh 2
.SH NAME
test.sh \- list the contents of directory
.SH SYNOPSIS
.B test.sh
[OPTION]...
[FILE]...
.SH DESCRIPTION
.B test.sh(2)
This is a sample script that list the content of a directory. There are only 2 options 'l' list the contents or 'a' list all the contents with hidden files.
.SH OPTIONS
.TP
.BR l
Long Listing the content, with permissions,ownership,block size, file sizes etc..
.TP
.BR a
Lists all contents including hidden files
